top=../..
include ${top}/Makefile.inc
headers= aarch64.h addrinfo.h board.h boot64.h ctxsw.h exception.h gic-pl390.h hal.h \
	hal_types.h irq.h psw.h thread_info.h timer.h
all:
clean:

distclean:
	${RM} \#* *~
