top=../..
include ${top}/Makefile.inc
headers= asm-offset-helper.h bitops.h errno.h freestanding.h heap.h id_bitmap.h \
	idle_thread.h irq.h kconsole.h kern_types.h kernel.h list.h main.h malloc-params.h \
	malloc.h mutex.h param.h printf.h ready_que.h reaper.h sched.h string.h \
	thread.h thread_manager.h timer.h wqueue.h

all:

distclean:
	${RM} \#* *~
