top=../..
include ${top}/Makefile.inc
headers=addrinfo.h boot64.h ctxsw.h exception.h hal.h hal_types.h linkage.h \
	multiboot.h port.h psw.h raw_console.h segments.h thread_info.h
all:
clean:

distclean:
	${RM} \#* *~
