top=..
include ${top}/Makefile.inc
CFLAGS += -I${top}/include
objects=
lib=libXXXX.a

all:${lib}

${lib}:${objects}
	${AR} ${ARFLAGS} $@ $^
	${RANLIB} $@
clean:
	${RM} *.o ${lib}

distclean:clean
	${RM} *~
